/**
 * Created by zhubg on 2017/4/17.
 */

'use strict';

Object.defineProperty(exports, "__esModule", {
    value: true
});
var typeDefs = exports.typeDefs = '\n\n#\u5206\u9875\u6D88\u606F\ntype PageInfo {\n    endCursor: Int!\n    hasNextPage: Boolean!\n}\n\n#\u8F6F\u4EF6\ntype Software {\n    version: String!\n    title: String!\n    modified_date: String!\n}\n\n#\u76D1\u63A7\u70B9\u7C7B\u578B\ntype MonitorType {\n    title: String!\n}\n\n#\u76D1\u63A7\u70B9\ntype MonitorPoint {\n    default_value: String!\n    important: Boolean!\n    monitor_type: MonitorType!\n    title: String!\n    value_type: String!\n    value_unit: String!\n}\n\n#\u89C4\u5219\ntype Rule {\n    title: String!\n    description: String!\n    monitor_type: MonitorType!\n    d_rule_type: String!\n    d_rule_class: String!\n    d_top: String!\n    d_floor: String!\n    top_symbol: String!\n    floor_symbol: String!\n    d_time_value: String!\n    d_time_unit: String!\t        \n    d_time_symbol: String!\t     \n    e_rule_class: String!\t    \n    e_top: String!\t            \n    e_floor: String!\t            \n    e_time_value: String!\t    \n    e_time_unit: String!\t        \n    e_time_symbol: String!\n}\n\n#\u8BBE\u5907\u76D1\u63A7\u70B9\u5173\u7CFB\u8868\ntype MonitorPointListItem {\n    value: String!\n    time_value: String!            \n    monitorPoint_status: String!  \n    modified: String!\n    monitorPoint: MonitorPoint!\n    rule: Rule! \n    monitor_type: MonitorType!           \n}\n\n#\u8BBE\u5907\ntype Device {\n    id: String!\n    title: String!\n    role: String!\n    department: String!\n    device_type: String!\n    device_object_id: String!\n    device_object: String!\n    username: String!\n    password: String!\n    description: String!\n    brand: String!\n    model_number: String!\n    cpu: String!\n    mem: String!\n    disk: String!\n    ip: String!\n    operate_system: String!\n    up_time: String!\n    softwareList:[Software]\n    monitorPointList: [MonitorPointListItem]\n}\n\ntype DeviceList {\n    totalCount: Int!\n    deviceList: [Device]\n    pageInfo: PageInfo!\n}\n\ntype Token {\n    token: String!\n}\n\ntype Message {\n    type: String!\n    code: String!\n    content: String!\n}\n\n#\u8F93\u5165\u7C7B\u578B\u5173\u952E\u5B57input\n\n#\u8054\u5408\u7C7B\u578BGetTokenResult\nunion GetTokenResult =  Token | Message\n\n#\u8054\u5408\u7C7B\u578BGetDeviceListResult\nunion GetDeviceListResult =  DeviceList | Message\n\ntype Query {\n    getToken(id:ID!): GetTokenResult!\n    getDeviceListResult(offset:Int!,count:Int!): GetDeviceListResult!\n}\n\nschema {\n  query: Query\n}\n\n';